### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by PanierAvide** [cquest/sgblur#11]
To make it integrable in ready-to-use [Docker files](https://gitlab.com/geovisio/api/-/blob/develop/docker/docker-compose-blurring.yml) offered in GeoVisio API (for at least simpler testing on local deployment), this would be interesting to have a Dockerfile of SGBlur API :wink:

**Comment by cquest** [comment]
See https://github.com/cquest/sgblur/pull/32
