### ISSUE TITLE
Décalage d'image floutée

### ISSUE THREAD

**Issue by PanierAvide** [cquest/sgblur#48]
Rapporté par @overflorian de base ici https://gitlab.com/geovisio/web-viewer/-/issues/93

Hello,
La tête de cette personne est bien floutée mais l'image floutée est décalée, laissant apparaitre un espace gris https://panoramax.openstreetmap.fr/#background=streets&focus=pic&map=16.67/48.913996/2.345619&pic=574b45a3-c95b-4051-9912-425c68a6959f&speed=250&xyz=146.37/-19.82/27

![image](https://gitlab.com/geovisio/web-viewer/uploads/755cf6158e11dd673403a52ae54c4a3e/image.png)

trop bizarre comme bug, help

**Comment by cquest** [comment]
C'est un bug corrigé... mais les photos déjà floutées ne peuvent être corrigées :(
